openapi: 3.0.0

info:
  title: Repository Search API
  version: 1.0.0
  description: Abstraction of GitHub's Search and Repository API.

paths:
  /api/v1/repos/search:
    get:
      summary: Abstraction of GitHub Search API.
      description: Abstraction of GitHub Search API.
      externalDocs:
        description: GitHub Repository Search API Docs
        url: https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-repositories
      parameters:
        - in: query
          name: firstCreationDate
          schema:
            type: string
          required: true
          description: YYYY-MM-DD
          example: "2013-05-01"
        - in: query
          name: lastCreationDate
          schema:
            type: string
          required: true
          description: YYYY-MM-DD
          example: "2013-05-01"
        - in: query
          name: language
          schema:
            type: string
          required: true
          example: Go
        - in: query
          name: minStars
          schema:
            type: string
          required: true
          description: Minimum Stars repository must have.
          example: "100"
        - in: query
          name: maxStars
          schema:
            type: string
          required: true
          description: Max Stars repository must have. If set to 0, it will be considered as no limit.
          example: "10000"
        - in: query
          name: order
          schema:
            type: string
            enum: [ asc, desc ]
            default: desc
          required: false
          description: The order of the results, either ascending (asc) or descending (desc). Defaults to descending.
          example: desc
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_count:
                    type: integer
                    description: The total number of repositories found.
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Repository'
                required:
                  - total_count
                  - items
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error Message.
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error Message.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error Message.
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error Message.
      security:
        - ApiKeyAuth: [ ]
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Required GitHub Personal Access Token to authenticate requests for increased rate limits.
  schemas:
    Repository:
      type: object
      properties:
        name:
          type: string
        full_name:
          type: string
        created_at:
          type: string
          format: date-time
        stargazer_count:
          type: integer
        language:
          type: string
        open_issues:
          type: integer
        closed_issues:
          type: integer
        open_pull_request_count:
          type: integer
        closed_pull_request_count:
          type: integer
        forks:
          type: integer
        subscriber_count:
          type: integer
        watcher_count:
          type: integer
        commit_count:
          type: integer
        network_count:
          type: integer
        latest_release:
          type: string
        total_releases_count:
          type: integer
        contributor_count:
          type: integer
        third_party_loc:
          type: integer
        self_written_loc:
          type: integer
